configMapGenerator:
- name: example-configmap-1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: core.harbor.domain/test/devwiki-backend
  newTag: c3e4e6af30b9965c16fe8185a0e0bef59a57f59b
