configMapGenerator:
- name: example-configmap-1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: core.harbor.domain/test/devwiki-backend
  newTag: 527c76126b7e172ca6c58f8fbf12998e1f261303
